; setup.iss - Inno Setup Script for Helix
; Install Inno Setup (fromjrsoftware.org) and open this file to compile Helix_Setup.exe

[Setup]
AppName=Helix
AppVersion=1.0.0
AppPublisher=Invenesis
AppPublisherURL=https://invenesis.com
DefaultDirName={autopf}\Helix
DefaultGroupName=Helix
DisableProgramGroupPage=yes
; Place output setup.exe in the parent directory of build
OutputDir=.
OutputBaseFilename=Helix_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=resources\icons\Sphere.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main Executable
Source: "dist\Helix.exe"; DestDir: "{app}"; Flags: ignoreversion

; Deployed Qt DLLs, Plugins, and folders (generated by windeployqt)
Source: "dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.obj, *.pdb, *.ilk, *.lib, *.exp"

[Icons]
Name: "{group}\Helix"; Filename: "{app}\Helix.exe"
Name: "{autodesktop}\Helix"; Filename: "{app}\Helix.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Helix.exe"; Description: "{cm:LaunchProgram,Helix}"; Flags: nowait postinstall skipifsilent
