; setup.iss - Inno Setup Script for Helix
; Install Inno Setup (fromjrsoftware.org) and open this file to compile Helix_Setup.exe

[Setup]
AppName=Helix
AppVersion=1.1.0
AppPublisher=Invenesis
AppPublisherURL=https://invenesis.com
DefaultDirName={autopf}\Helix
DefaultGroupName=Helix
DisableProgramGroupPage=yes
; Place output setup.exe in the parent directory of build
OutputDir=.
OutputBaseFilename=Helix_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=resources\icons\application.ico
ChangesEnvironment=yes
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main Executable
Source: "dist\Helix.exe"; DestDir: "{app}"; Flags: ignoreversion

; Deployed Qt DLLs, Plugins, and folders (generated by windeployqt)
Source: "dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.obj, *.pdb, *.ilk, *.lib, *.exp"

[Icons]
Name: "{group}\Helix"; Filename: "{app}\Helix.exe"
Name: "{autodesktop}\Helix"; Filename: "{app}\Helix.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Helix.exe"; Description: "{cm:LaunchProgram,Helix}"; Flags: nowait postinstall skipifsilent

[Code]
var
  DbPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  // Create a custom page for database settings right afterwpSelectDir
  DbPage := CreateInputQueryPage(wpSelectDir,
    'Database Configuration', 'Please enter your PostgreSQL connection details',
    'These settings will be saved as environment variables for Helix. If they already exist on your system, they will be loaded as defaults.');

  // Add input fields (label, password mask)
  DbPage.Add('Database Host (INV_DB_HOST):', False);
  DbPage.Add('Database Name (INV_DB_NAME):', False);
  DbPage.Add('Database User (INV_DB_USER):', False);
  DbPage.Add('Database Password (INV_DB_PASSWORD):', True);
  DbPage.Add('Database Port (INV_DB_PORT):', False);

  // Load existing environment variables as defaults if available
  DbPage.Values[0] := GetEnv('INV_DB_HOST');
  DbPage.Values[1] := GetEnv('INV_DB_NAME');
  DbPage.Values[2] := GetEnv('INV_DB_USER');
  DbPage.Values[3] := GetEnv('INV_DB_PASSWORD');
  DbPage.Values[4] := GetEnv('INV_DB_PORT');
  
  if DbPage.Values[4] = '' then
    DbPage.Values[4] := '5432';
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    // Save the values to the system-wide environment registry key (broadcasts change due to ChangesEnvironment=yes)
    RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'INV_DB_HOST', DbPage.Values[0]);
    RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'INV_DB_NAME', DbPage.Values[1]);
    RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'INV_DB_USER', DbPage.Values[2]);
    RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'INV_DB_PASSWORD', DbPage.Values[3]);
    RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'INV_DB_PORT', DbPage.Values[4]);
  end;
end;
